# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Github/releases/Cmod-A7/Cmod-A7-35T-GPIO/proj/Cmod-A7-35T-GPIO.cache/wt [current_project]
set_property parent.project_path D:/Github/releases/Cmod-A7/Cmod-A7-35T-GPIO/proj/Cmod-A7-35T-GPIO.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part_repo_paths D:/Github/vivado-boards/new/board_files [current_project]
set_property board_part digilentinc.com:cmod_a7-35t:part0:1.1 [current_project]
set_property ip_repo_paths d:/Github/releases/Cmod-A7/Cmod-A7-35T-GPIO/repo [current_project]
set_property ip_output_repo d:/Github/releases/Cmod-A7/Cmod-A7-35T-GPIO/repo/cache [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/Github/releases/Cmod-A7/Cmod-A7-35T-GPIO/src/hdl/RGB_controller.vhd
  D:/Github/releases/Cmod-A7/Cmod-A7-35T-GPIO/src/hdl/UART_TX_CTRL.vhd
  D:/Github/releases/Cmod-A7/Cmod-A7-35T-GPIO/src/hdl/debouncer.vhd
  D:/Github/releases/Cmod-A7/Cmod-A7-35T-GPIO/src/hdl/GPIO.vhd
}
read_ip -quiet D:/Github/releases/Cmod-A7/Cmod-A7-35T-GPIO/src/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all d:/Github/releases/Cmod-A7/Cmod-A7-35T-GPIO/src/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Github/releases/Cmod-A7/Cmod-A7-35T-GPIO/src/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all d:/Github/releases/Cmod-A7/Cmod-A7-35T-GPIO/src/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Github/releases/Cmod-A7/Cmod-A7-35T-GPIO/src/constraints/CmodA7_Master.xdc
set_property used_in_implementation false [get_files D:/Github/releases/Cmod-A7/Cmod-A7-35T-GPIO/src/constraints/CmodA7_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top GPIO_demo -part xc7a35tcpg236-1 -flatten_hierarchy none -directive RuntimeOptimized -fsm_extraction off


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef GPIO_demo.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file GPIO_demo_utilization_synth.rpt -pb GPIO_demo_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
